import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthProvider } from 'app/hooks/useAuth'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
      <AuthProvider>
        <main id='root' className='w-full main flex-auto justify-center h-screen content-center'>{children}</main>
      </AuthProvider>
      </body>
    </html>
  );
}
